
DEAL::Exception caught as expected.
DEAL::test_1=1,0,1
